Task_1_2_1
buljad/OOP pull request #8
Opened 2022-10-12 20:44 UTC by buljad

[Настя, извините, что так поздно! Я во вторник заболел и не смог прийти вчера на пару :(

2022-10-19 05:59 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/izhuravskii/Stack.java
> +        }
Понять

2022-10-19 05:59 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/izhuravskii/Stack.java
> +        }
Arrays.equals(_, _, _, _, _)

2022-10-23 13:13 UTC, buljad commented on Task_1_2_1/src/main/java/ru/nsu/izhuravskii/Stack.java
> +        }
Заменил, теперь вроде готово

2022-10-31 09:02 UTC, shadrina requested changes
В остальном ок

2022-10-31 09:02 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/izhuravskii/Stack.java
> +        }
Метод называется `pushStack`, почему аргумент -- массив?

2022-10-31 09:02 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/izhuravskii/Stack.java
> +        }
Давай проще и быстрее с модификацией состояния прямо отсюда, без `num` вызовов другого метода.

2022-11-07 10:09 UTC, shadrina approved these changes
Задача сдана, но прежде чем мерджить нужно загитигнорить и убрать папку make.

2022-11-08 02:16 UTC, buljad commented
Загитигнорил и убрал make

2022-11-08 02:18 UTC, merged